//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCS-SR-Server.Assets.Lang.Resources.zh-CN", typeof(Resources_zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 封禁.
        /// </summary>
        internal static string BtnBan {
            get {
                return ResourceManager.GetString("BtnBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户端管理.
        /// </summary>
        internal static string BtnClientAdmin {
            get {
                return ResourceManager.GetString("BtnClientAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关.
        /// </summary>
        internal static string BtnDisabled {
            get {
                return ResourceManager.GetString("BtnDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开.
        /// </summary>
        internal static string BtnEnabled {
            get {
                return ResourceManager.GetString("BtnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 踢出.
        /// </summary>
        internal static string BtnKick {
            get {
                return ResourceManager.GetString("BtnKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 静音.
        /// </summary>
        internal static string BtnMute {
            get {
                return ResourceManager.GetString("BtnMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关.
        /// </summary>
        internal static string BtnOff {
            get {
                return ResourceManager.GetString("BtnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开.
        /// </summary>
        internal static string BtnOn {
            get {
                return ResourceManager.GetString("BtnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始服务器.
        /// </summary>
        internal static string BtnStartServer {
            get {
                return ResourceManager.GetString("BtnStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 停止服务器.
        /// </summary>
        internal static string BtnStopServer {
            get {
                return ResourceManager.GetString("BtnStopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传输存档时间.
        /// </summary>
        internal static string LabelArchiveTime {
            get {
                return ResourceManager.GetString("LabelArchiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检查Beta版更新.
        /// </summary>
        internal static string LabelCheckBetaUpdates {
            get {
                return ResourceManager.GetString("LabelCheckBetaUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户端:.
        /// </summary>
        internal static string LabelClients {
            get {
                return ResourceManager.GetString("LabelClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传输距离限制.
        /// </summary>
        internal static string LabelDistanceLimit {
            get {
                return ResourceManager.GetString("LabelDistanceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动导出列表.
        /// </summary>
        internal static string LabelExportList {
            get {
                return ResourceManager.GetString("LabelExportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 外部预警机模式 (EAM).
        /// </summary>
        internal static string LabelExternalAWACS {
            get {
                return ResourceManager.GetString("LabelExternalAWACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAM蓝方密码.
        /// </summary>
        internal static string LabelExternalAWACSBluePass {
            get {
                return ResourceManager.GetString("LabelExternalAWACSBluePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAM红方密码.
        /// </summary>
        internal static string LabelExternalAWACSRedPass {
            get {
                return ResourceManager.GetString("LabelExternalAWACSRedPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局大厅频率 AM (MHz).
        /// </summary>
        internal static string LabelGlobalLobbyFreq {
            get {
                return ResourceManager.GetString("LabelGlobalLobbyFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地形遮挡检测.
        /// </summary>
        internal static string LabelLOS {
            get {
                return ResourceManager.GetString("LabelLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotATC应答机导出.
        /// </summary>
        internal static string LabelLotATCExport {
            get {
                return ResourceManager.GetString("LabelLotATCExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 大厅无视无线电效果.
        /// </summary>
        internal static string LabelOverrideEffectsOnGlobal {
            get {
                return ResourceManager.GetString("LabelOverrideEffectsOnGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 端口:.
        /// </summary>
        internal static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 允许无线电加密.
        /// </summary>
        internal static string LabelRadioEncryption {
            get {
                return ResourceManager.GetString("LabelRadioEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展无线电.
        /// </summary>
        internal static string LabelRadioExpansion {
            get {
                return ResourceManager.GetString("LabelRadioExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真实无线电接收.
        /// </summary>
        internal static string LabelRealRx {
            get {
                return ResourceManager.GetString("LabelRealRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 真实无线电发送.
        /// </summary>
        internal static string LabelRealTx {
            get {
                return ResourceManager.GetString("LabelRealTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转发节点数限制.
        /// </summary>
        internal static string LabelRetransmitNodeLimit {
            get {
                return ResourceManager.GetString("LabelRetransmitNodeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保护阵营无线电.
        /// </summary>
        internal static string LabelSecurity {
            get {
                return ResourceManager.GetString("LabelSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示发送者名字.
        /// </summary>
        internal static string LabelShowTransmitterName {
            get {
                return ResourceManager.GetString("LabelShowTransmitterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 观众席语音.
        /// </summary>
        internal static string LabelSpectator {
            get {
                return ResourceManager.GetString("LabelSpectator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 严格无线电加密.
        /// </summary>
        internal static string LabelStrictEncryption {
            get {
                return ResourceManager.GetString("LabelStrictEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自我测试频率 AM (MHz).
        /// </summary>
        internal static string LabelTestFreq {
            get {
                return ResourceManager.GetString("LabelTestFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录收到的传输.
        /// </summary>
        internal static string LabelTransmissionLog {
            get {
                return ResourceManager.GetString("LabelTransmissionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示同频人数.
        /// </summary>
        internal static string LabelTunedCount {
            get {
                return ResourceManager.GetString("LabelTunedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRS 客户端列表.
        /// </summary>
        internal static string TitleClientList {
            get {
                return ResourceManager.GetString("TitleClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS-SRS 服务器.
        /// </summary>
        internal static string TitleServer {
            get {
                return ResourceManager.GetString("TitleServer", resourceCulture);
            }
        }
    }
}
