//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCS {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCS-SR-Server.Assets.Lang.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ban!.
        /// </summary>
        internal static string BtnBan {
            get {
                return ResourceManager.GetString("BtnBan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Admin.
        /// </summary>
        internal static string BtnClientAdmin {
            get {
                return ResourceManager.GetString("BtnClientAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISABLED.
        /// </summary>
        internal static string BtnDisabled {
            get {
                return ResourceManager.GetString("BtnDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENABLED.
        /// </summary>
        internal static string BtnEnabled {
            get {
                return ResourceManager.GetString("BtnEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kick.
        /// </summary>
        internal static string BtnKick {
            get {
                return ResourceManager.GetString("BtnKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string BtnMute {
            get {
                return ResourceManager.GetString("BtnMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string BtnOff {
            get {
                return ResourceManager.GetString("BtnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string BtnOn {
            get {
                return ResourceManager.GetString("BtnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Server.
        /// </summary>
        internal static string BtnStartServer {
            get {
                return ResourceManager.GetString("BtnStartServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Server.
        /// </summary>
        internal static string BtnStopServer {
            get {
                return ResourceManager.GetString("BtnStopServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission Archive Time.
        /// </summary>
        internal static string LabelArchiveTime {
            get {
                return ResourceManager.GetString("LabelArchiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for beta updates.
        /// </summary>
        internal static string LabelCheckBetaUpdates {
            get {
                return ResourceManager.GetString("LabelCheckBetaUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients:.
        /// </summary>
        internal static string LabelClients {
            get {
                return ResourceManager.GetString("LabelClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance Limit.
        /// </summary>
        internal static string LabelDistanceLimit {
            get {
                return ResourceManager.GetString("LabelDistanceLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Export List.
        /// </summary>
        internal static string LabelExportList {
            get {
                return ResourceManager.GetString("LabelExportList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External AWACS Mode (EAM).
        /// </summary>
        internal static string LabelExternalAWACS {
            get {
                return ResourceManager.GetString("LabelExternalAWACS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAM blue coal. password.
        /// </summary>
        internal static string LabelExternalAWACSBluePass {
            get {
                return ResourceManager.GetString("LabelExternalAWACSBluePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAM red coal. password.
        /// </summary>
        internal static string LabelExternalAWACSRedPass {
            get {
                return ResourceManager.GetString("LabelExternalAWACSRedPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Lobby Freq. AM (MHz).
        /// </summary>
        internal static string LabelGlobalLobbyFreq {
            get {
                return ResourceManager.GetString("LabelGlobalLobbyFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line of Sight.
        /// </summary>
        internal static string LabelLOS {
            get {
                return ResourceManager.GetString("LabelLOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LotATC Transponder Export.
        /// </summary>
        internal static string LabelLotATCExport {
            get {
                return ResourceManager.GetString("LabelLotATCExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore Radio Effect on Global Freq.
        /// </summary>
        internal static string LabelOverrideEffectsOnGlobal {
            get {
                return ResourceManager.GetString("LabelOverrideEffectsOnGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        internal static string LabelPort {
            get {
                return ResourceManager.GetString("LabelPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Radio Encryption.
        /// </summary>
        internal static string LabelRadioEncryption {
            get {
                return ResourceManager.GetString("LabelRadioEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Expansion.
        /// </summary>
        internal static string LabelRadioExpansion {
            get {
                return ResourceManager.GetString("LabelRadioExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRL Radio Rx Behaviour.
        /// </summary>
        internal static string LabelRealRx {
            get {
                return ResourceManager.GetString("LabelRealRx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRL Radio Tx Behaviour.
        /// </summary>
        internal static string LabelRealTx {
            get {
                return ResourceManager.GetString("LabelRealTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retransmit Hop/Node Count.
        /// </summary>
        internal static string LabelRetransmitNodeLimit {
            get {
                return ResourceManager.GetString("LabelRetransmitNodeLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Coalition Radios.
        /// </summary>
        internal static string LabelSecurity {
            get {
                return ResourceManager.GetString("LabelSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Transmitter Name.
        /// </summary>
        internal static string LabelShowTransmitterName {
            get {
                return ResourceManager.GetString("LabelShowTransmitterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectator Audio.
        /// </summary>
        internal static string LabelSpectator {
            get {
                return ResourceManager.GetString("LabelSpectator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict Radio Encryption.
        /// </summary>
        internal static string LabelStrictEncryption {
            get {
                return ResourceManager.GetString("LabelStrictEncryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Frequencies AM (MHz).
        /// </summary>
        internal static string LabelTestFreq {
            get {
                return ResourceManager.GetString("LabelTestFreq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Received Transmissions.
        /// </summary>
        internal static string LabelTransmissionLog {
            get {
                return ResourceManager.GetString("LabelTransmissionLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tuned/Client Count.
        /// </summary>
        internal static string LabelTunedCount {
            get {
                return ResourceManager.GetString("LabelTunedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SR Client List.
        /// </summary>
        internal static string TitleClientList {
            get {
                return ResourceManager.GetString("TitleClientList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCS-SRS Server.
        /// </summary>
        internal static string TitleServer {
            get {
                return ResourceManager.GetString("TitleServer", resourceCulture);
            }
        }
    }
}
